-- ============================================================
--  network - siec polaczen (statki, promy, dylizansy, wozy) dla /trasa
--
--  stops[room_id] = { gps = "...", city = "..." }
--    gps  - nazwa z "GPS: <nazwa>" lokalizatora (mapper/localizers/ships_buses),
--           cel dla /podroz; nil = lokalizator nie melduje przystanku
--    city - grupa do wyszukiwania po nazwie (domyslnie gps)
--
--  routes = { { id, type, name, line | cycle, times, verified } }
--    type  - "statek" | "dylizans" (jak w /podroz: rozne komendy wyjscia)
--    line  - przystanki tam i z powrotem: a, b, c, b, a, ...
--    cycle - przystanki w kolko: a, b, c, a, ...
--    times - sekundy miedzy kolejnymi przystankami (line: w jedna strone,
--            cycle: lacznie z powrotem na pierwszy); nil = domyslny czas
--    verified = false - kolejnosc przystankow wzieta z lokalizatora, nie
--            z definicji przejazdu (skrypty/transport/definitions)
-- ============================================================

scripts.transport_network = {
    stops = {
        -- Redania / Temeria
        [180]   = { gps = "Maribor" },
        [266]   = { gps = "Carreras" },
        [536]   = { gps = "Bialy Kiel" },
        [680]   = { gps = "Zajazd w Lyrii", city = "Lyria" },
        [729]   = { gps = "Wyzima" },
        [746]   = { gps = "Bialy Most" },
        [764]   = { gps = "Piana" },
        [790]   = { gps = "Polnoc Oxen", city = "Oxenfurt" },
        [804]   = { gps = "Oxenfurt" },
        [829]   = { gps = "Novigrad" },
        [860]   = { gps = "Scala" },
        [927]   = { gps = "Scala" },
        [994]   = { gps = "Rivia" },
        [1896]  = { gps = "Murivel" },
        [1998]  = { gps = "Rinde" },
        [2188]  = { gps = "Bialy Most" },
        [2212]  = { gps = "Bialy Most" },
        [2223]  = { gps = "Novigrad" },
        [2464]  = { gps = "Oxenfurt" },
        [2467]  = { gps = "Oxenfurt" },
        [2574]  = { gps = "Oxenfurt" },
        [2616]  = { gps = "Piana" },
        [2624]  = { gps = "Poludniowy brzeg Pontaru", city = "Piana" },
        [3043]  = { gps = "Brugge" },
        [3221]  = { gps = "Obawa", city = "Bodrog" },
        [3247]  = { gps = "Twierdza Bodrog", city = "Bodrog" },
        [3248]  = { gps = "Twierdza Bodrog", city = "Bodrog" },
        [3251]  = { gps = "Bodrog" },
        [3273]  = { gps = "Twierdza Rozrog", city = "Rozrog" },
        [3280]  = { gps = "Twierdza Rozrog", city = "Rozrog" },
        [3281]  = { gps = "Twierdza Rozrog", city = "Rozrog" },
        [3343]  = { gps = "Zajazd przy Osadzie" },
        [3442]  = { gps = "Polnocny brzeg Pontaru", city = "Temeria" },
        [3457]  = { gps = "Kocie Pole" },
        [3525]  = { gps = "Grabowa Buchta" },
        [3542]  = { gps = "Grabowa Buchta" },
        [3583]  = { gps = "Nadrzecze" },
        [3760]  = { gps = "Anchor" },
        [3926]  = { gps = "Podgrodzie Tretogoru", city = "Tretogor" },
        [4058]  = { gps = "Blaviken" },
        [4059]  = { gps = "Blaviken" },
        [4060]  = { gps = "Blaviken" },
        [4061]  = { gps = "Blaviken" },
        [4092]  = { gps = "Sucha Kepa" },
        [4163]  = { gps = "Gelibol" },
        [7903]  = { gps = "Porty Poludniowe Novigradu", city = "Novigrad" },
        [7907]  = { gps = "Porty Poludniowe Novigradu", city = "Novigrad" },
        [7908]  = { gps = "Porty Poludniowe Novigradu", city = "Novigrad" },
        [7909]  = { gps = "Novigrad" },
        [7910]  = { gps = "Porty Poludniowe Novigradu", city = "Novigrad" },
        [7911]  = { gps = "Porty Poludniowe Novigradu", city = "Novigrad" },
        [7912]  = { gps = "Porty Poludniowe Novigradu", city = "Novigrad" },
        [8087]  = { gps = "Dolina Kwiatow" },
        [9990]  = { gps = "Hagge" },
        [10018] = { gps = "Hagge" },
        [10486] = { gps = "Stocznia Novigradzka" },
        [11153] = { gps = "Wyspa Slubow" },
        [11154] = { gps = "Wyspa Slubow" },
        [11690] = { gps = "Daevon" },
        -- Skellige
        [10311] = { gps = "Ard Skellige" },
        [10313] = { gps = "Ard Skellige" },
        [10314] = { gps = "Ard Skellige" },
        [10369] = { gps = "Skellige", city = "Ard Skellige" },
        [23669] = { gps = "Faroe" },
        [23678] = { gps = "Hindersfjall" },
        [23685] = { gps = "Spikeroog (d. Kaer Hemdall)", city = "Spikeroog" },
        -- Baccala
        [9705]  = { gps = "Baccala" },
        [9707]  = { gps = "Baccala" },
        [23708] = { gps = "Mekan" },
        [23792] = { gps = "Mekan" },
        -- Bretonia
        [4651]  = { gps = "Quenelles" },
        [4653]  = { gps = "Quenelles" },
        [4659]  = { gps = "Quenelles" },
        [4824]  = { gps = "Polnocny Zachod Quenelles", city = "Quenelles" },
        [4841]  = { gps = "Zachod Quenelles", city = "Quenelles" },
        [4890]  = { gps = "Marguilles" },
        [4922]  = { gps = "Salignac La Rouge", city = "Salignac" },
        [4985]  = { gps = "'Pod Piegowata Elfka'" },
        [7732]  = { gps = "Parravon" },
        [7733]  = { gps = "Bretonia" },
        [7744]  = { gps = "Merceaux-Descloux" },
        [7786]  = { gps = "Montlac" },
        [26659] = { gps = "Parravon" },
        -- Tilea
        [5308]  = { gps = "Toscania" },
        [5373]  = { gps = "Ebino" },
        [5439]  = { gps = "Miragliano" },
        [5468]  = { gps = "Campogrotta" },
        [5601]  = { gps = "Alimento" },
        [5625]  = { gps = "Viadaza" },
        [5842]  = { gps = "Urbimo" },
        [5887]  = { gps = "Urbimo" },
        [5946]  = { gps = "Urbimo" },
        [5947]  = { gps = "Urbimo" },
        [5985]  = { gps = "Varieno" },
        -- Imperium
        [5200]  = { gps = "Kreutzhofen" },
        [5206]  = { gps = "Kreutzhofen" },
        [5207]  = { gps = "Kreutzhofen" },
        [6427]  = { gps = "Blekitna Wstega" },
        [6428]  = { gps = "Blekitna Wstega" },
        [6429]  = { gps = "Blekitna Wstega" },
        [6430]  = { gps = "Blekitna Wstega" },
        [6448]  = { gps = "Podzamcze Twierdzy Sigmarytow" },
        [6520]  = { gps = "Averheim" },
        [6571]  = { gps = "Przed zajazdem Czarny Kon", city = "Czarny Kon" },
        [6621]  = { gps = "Kraina Zgromadzenia" },
        [6727]  = { gps = "Kraina Zgromadzenia" },
        [6779]  = { gps = "Wioska miedzy Nuln a KZ", city = "Blutdorf" },
        [6879]  = { gps = "Wschod Nuln", city = "Nuln" },
        [6891]  = { gps = "Nuln" },
        [6903]  = { gps = "Poludnie Nuln", city = "Nuln" },
        [7086]  = { gps = "Heideck" },
        [7131]  = { gps = "Tadrig" },
        [7233]  = { gps = "Porty Nuln", city = "Nuln" },
        [7256]  = { gps = "Polnoc Nuln", city = "Nuln" },
        [7332]  = { gps = "Zachod Nuln", city = "Nuln" },
        [7458]  = { gps = "Ubersreik" },
        [7550]  = { gps = "Bogenhafen" },
        [7568]  = { gps = "Bogenhafen" },
        [7640]  = { gps = "Jouinard" },
        [15409] = { gps = "Karak Varn" },
    },

    routes = {
        -- dylizanse i wozy
        { id = "jouinard-nuln", type = "dylizans", name = "Jouinard - Nuln",
          line = { 7640, 7550, 7458, 7332 }, times = { 42, 27, 37 } },
        { id = "kz-nuln", type = "dylizans", name = "Kraina Zgromadzenia - Nuln",
          line = { 6727, 6571, 6779, 7256 }, times = { 19, 17, 27 } },
        { id = "maribor-grabowa", type = "dylizans", name = "Maribor - Grabowa Buchta",
          line = { 180, 3343, 3457, 3525 }, times = { 43, 38, 22 } },
        { id = "salignac-nuln", type = "dylizans", name = "Salignac - Nuln",
          line = { 4922, 4985, 5200, 6903 }, times = { 12, 50, 49 } },
        { id = "campogrotta-varieno", type = "dylizans", name = "Campogrotta - Varieno",
          line = { 5468, 5439, 5625, 5842, 5985 }, times = { 25, 15, 15, 25 } },
        { id = "wyzima-oxenfurt", type = "dylizans", name = "Wyzima - Oxenfurt",
          line = { 729, 3760, 746, 764, 790 }, times = { 19, 23, 15, 21 } },
        { id = "bialymost-hagge", type = "dylizans", name = "Bialy Most - Hagge",
          line = { 2188, 1998, 1896, 9990 }, verified = false },
        { id = "carreras-lyria", type = "dylizans", name = "Carreras - Lyria",
          line = { 266, 994, 860, 680 }, verified = false },
        { id = "tretogor-gelibol", type = "dylizans", name = "Tretogor - Gelibol",
          line = { 3926, 4092, 4163 }, verified = false },
        { id = "maribor-verden", type = "dylizans", name = "Maribor - Verden",
          line = { 180, 536, 3043, 3221 }, verified = false },
        { id = "novigrad-oxenfurt", type = "dylizans", name = "Novigrad - Oxenfurt",
          line = { 829, 804 }, verified = false },
        { id = "nuln-blekitna", type = "dylizans", name = "Nuln - Blekitna Wstega",
          line = { 6879, 7131, 7086, 6520, 6448, 6430 }, verified = false },
        { id = "quenelles-parravon", type = "dylizans", name = "Quenelles - Parravon",
          line = { 4659, 7786, 7744, 26659 }, verified = false },
        { id = "urbimo-toscania", type = "dylizans", name = "Urbimo - Toscania",
          line = { 5887, 5373, 5308 }, verified = false },

        -- statki, promy, tratwy
        { id = "ancelmus", type = "statek", name = "Ancelmus (Blekitna Wstega - KZ - Nuln - Kreutzhofen)",
          line = { 6429, 6621, 7233, 5207 }, times = { 43, 44, 43 } },
        { id = "annibale", type = "statek", name = "Annibale (Urbimo - Novigrad)",
          line = { 5947, 7909 }, times = { 199 } },
        { id = "asa", type = "statek", name = "Asa (Ard Skellige - Faroe - Rozrog)",
          cycle = { 10313, 23669, 3280 }, times = { 55, 86, 29 } },
        { id = "batista", type = "statek", name = "Batista (Mekan - Baccala)",
          line = { 23792, 9707 }, times = { 93 } },
        { id = "bjorn", type = "statek", name = "Bjorn (Rozrog - Mekan)",
          line = { 3273, 23708 }, times = { 48 } },
        { id = "cern", type = "statek", name = "Cern (Urbimo - Wyspa Slubow)",
          line = { 5946, 11154 }, times = { 86 } },
        { id = "charonda", type = "statek", name = "Charonda (Novigrad - Rozrog - Baccala)",
          line = { 7910, 3281, 9705 }, times = { 107, 76 } },
        { id = "creyard", type = "statek", name = "Creyard (Nuln - Bogenhafen)",
          line = { 6891, 7568 }, times = { 42 } },
        { id = "daniel", type = "statek", name = "Daniel (Quenelles)",
          line = { 4841, 4824 }, times = { 30 } },
        { id = "elich", type = "statek", name = "Elich (Novigrad - Stocznia - Nadrzecze)",
          line = { 7903, 10486, 3583 }, times = { 28, 27 } },
        { id = "flavius", type = "statek", name = "Flavius (Novigrad - Blaviken - Daevon)",
          cycle = { 2223, 4061, 11690, 4058 }, times = { 45, 42, 55, 55 } },
        { id = "francois", type = "statek", name = "Francois (Quenelles - Bodrog)",
          line = { 4651, 3251 }, times = { 179 } },
        { id = "gervais", type = "statek", name = "Gervais (Quenelles - Marguilles)",
          line = { 4653, 4890 }, times = { 31 } },
        { id = "gmeath", type = "statek", name = "Gmeath (prom przez Pontar)",
          line = { 2624, 3442 }, times = { 25 } },
        { id = "gvidon", type = "statek", name = "Gvidon (Novigrad - Wyspa Slubow)",
          line = { 7911, 11153 }, times = { 89 } },
        { id = "hallgerda", type = "statek", name = "Hallgerda (Novigrad - Ard Skellige)",
          line = { 7907, 10311 }, times = { 60 } },
        { id = "haming", type = "statek", name = "Haming (Piana - Hagge - Dolina Kwiatow)",
          line = { 2616, 10018, 8087 }, times = { 42, 42 } },
        { id = "jacob", type = "statek", name = "Jacob (Blaviken - Blekitna Wstega)",
          line = { 4060, 6428 }, times = { 174 } },
        { id = "kelim", type = "statek", name = "Kelim (Bodrog - Novigrad - Scala)",
          cycle = { 3247, 7912, 3248, 927 }, times = { 73, 58, 56, 77 } },
        { id = "louis", type = "statek", name = "Louis (Parravon - Bretonia)",
          line = { 7732, 7733 }, times = { 25 } },
        { id = "luiggi", type = "statek", name = "Luiggi (Kreutzhofen - Alimento)",
          line = { 5206, 5601 }, times = { 58 } },
        { id = "malacius", type = "statek", name = "Malacius (Oxenfurt - Blaviken)",
          line = { 2574, 4059 }, times = { 55 } },
        { id = "mallcolm", type = "statek", name = "Mallcolm (Karak Varn - Blekitna Wstega)",
          line = { 15409, 6427 }, times = { 41 } },
        { id = "olaf", type = "statek", name = "Olaf (Ard Skellige - Hindersfjall)",
          line = { 10314, 23678 }, times = { 27 } },
        { id = "pluskolec", type = "statek", name = "Pluskolec (Novigrad - Oxenfurt - Bialy Most)",
          cycle = { 7908, 2467, 2212 }, times = { 40, 40, 30 } },
        { id = "rygwit", type = "statek", name = "Rygwit (Skellige - Spikeroog)",
          line = { 10369, 23685 }, times = { 29 } },
        { id = "strag", type = "statek", name = "Strag (Oxenfurt - Grabowa Buchta)",
          line = { 2464, 3542 }, times = { 31 } },
    },

    -- dodatkowe nazwy przy wyszukiwaniu: alias -> city lub gps
    aliases = {
        kz = "Kraina Zgromadzenia",
        bw = "Blekitna Wstega",
        obawa = "Bodrog",
        verden = "Bodrog",
        ["kaer hemdall"] = "Spikeroog",
        ["wyspa milosci"] = "Wyspa Slubow",
        ["stare buki"] = "Dolina Kwiatow",
    },
}
